### ISSUE TITLE
SonarRanges message discussion

### ISSUE THREAD

**Issue by lauralindzey** [apl-ocean-engineering/hydrographic_msgs#3]
This is the place for discussion of a message for MBES range data.

**Comment by valschmidt** [comment]
HI Laura,

Here are our comments:
*sorry this is so long!*

First, I think it’s a great start and we agree with all the suggested changes you’ve made to WHOI’s initial definition. 

I am of the opinion that unused field should be populated with NaN rather than zero. Zero is often a valid value leaving the intent unclear. It pains me to no end that ROS doesn’t adopt this convention. 

The name of the message definition “SonarRanges” could probably be changed. There are a lot of different kinds of sonar systems and this message seems pretty particular to multi beam. It might be better to include “MBES” in the message name somehow. And since it doesn’t actually include ranges, maybe that name is misplaced. “rawMBES.msg”? I’m not sure.

The comments for elevation angle, azimuth_angle and beam widths are described as “sonar reported” values. But I wonder if these should be defined more explicitly so their definition doesn’t change with every sonar vendor’s reporting convention. For example, for elevation angle one might say: “Along-track steering angle (about the y-axis) with respect to the transmit transducer face.” This requires anyone writing a driver to match the convention of the message, not the convention of the sonar and that’s probably best.

In my opinion, it is worth stating a coordinate reference frame for the sensor itself and then defining the angular measurements (if only parenthetically) as a rotation about a specific axis. The typical ROS reference frame convention would put X forward, Y to the left and Z up. That means elevation angle would be a rotation about Y, with positive rotations aft by the right-hand-rule.  Similarly beam pointing angle would be a rotation about X, positive to port. I realize that’s not intuitive. The conventions as they are, I must admit, more in keeping with my experience with MBES systems. But it seems prudent to be consistent with ROS conventions and not use a left-handed reference frame.

The “Intensity” value is always a difficult one. Is it in linear units as is often recorded by Reson systems, or dB as is typical in other systems? Also traditionally Reson has recorded beam “magnitude”, which was the actual digitized value from the ADC converter. But the term “Intensity” usually means the square of this value, as acoustic intensity is proportion to the square of the sensed pressure. I’m not sure what Reson is doing now to be honest. At a minimum I would change the name of this field to relative_intensity_dB. In this case, I think it is worthwhile to spell out the units explicitly in the field name, as it is a field rife with confusion. If you’re interested in some late night reading into the difficulty in properly calibrating and interpreting MB backscatter data, you can drift off to sleep reading this report: https://niwa.co.nz/static/BWSG_REPORT_MAY2015_web.pdf

Two fields that might be added are travel time uncertainty and beam pointing angle uncertainty. Admittedly most sonars do not report these values directly, but it is where all other uncertainty values are derived. I admit this is tough one. Reson reports depth uncertainty as a fraction of the depth measurement for the beam. Kongsberg reports uncertainty in x, y and z. When they are not otherwise provided, to a first approximation one can assume the beam pointing uncertainty is zero and calculate the range uncertainty as sigmaR = sin(beam_pointing_angle) * sigmaZ. But maybe this is too much to provide guidance for. In any event, it is really useful to provide an estimate of the uncertainty in the soundings if possible. I’m happy to talk more about this one if you want. 

Thanks for putting in the effort to create some common ground.

**Comment by valschmidt** [comment]
One other thing:

We are thinking to propose two message definitions for pointcloud2 messages for soundings from MBESs. One would be light-weight, and the second would include a 3x3 covariance for each sounding. The third would have a complete set of metadata (borrowing from SonarRanges) for troubleshooting. The repeated data structures would have the following fields (all float except `flag`). Your thoughts are welcome. 

-Val
        
        # Msg 1
        x
        y
        z
        relative_intensity_dB

        # Msg 2         
        x
        y
        z
        relative_intensity_dB 
        cov[[9]
        
        # Msg 3
        x
        y
        z
        cov[9]
        relative_intensity_dB 
        sound_speed
        flag
        elevation_angle
        azimuth_angle
        elevation_beamwidth
        azimuth_beamwidth
        two_way_travel_time
        transmit_delay

**Comment by CaptKrasno** [comment]
On coordinate frames and beam angles: 

**Comment 1:** I really think we don't want to make assumptions about the orientation of the sensor.  So I think Along track and across track are out.   What would those names mean for an upward looking, under-ice, multibeam system?    I think the current azimuth  and elevation is better but still a bit slippery. 

**Proposal 1:** I think we state what is physically going on.   Let's call these tx_angle and rx_angle.   This is what the sonar is actually reporting.   Even the existing comments say elevation_angle is the "Sonar-reported along-track steering angle (applied to tx beam)" and azimuth_angle is "Sonar-reported across-track steering angle (applied to rx beam)".  Why not just call the variables what they actually are?

**Comment 2:**  @valschmidt  I don't think we need to use  x foreward, y port, z down orientation for the multibeam.   Again, this assumes a sensor orientation.  

**Proposal 2:**   A:  I propose we follow the sensor_msgs/LaserScan Message convention which states x is straight out of the sensor, y is left of the sensor.   So for a conventional (downward looking) orientation +z is allong track, +x is depth, and +y is port.   This means no negative values and corresponds with the azimuth and elevation naming convention if we decide to stick with that.  (I think we should definitely use this one if we  stick with azimuth and elevation labels)

B: Alternatively, we could emulate sensor_msgs/Image which states that +z should point into to plane of the image.  I would suggest that the x axis line up with the +x vehicle axis.    So, in the conventional configuration,  +z is depth and +y is across track to starbaoard.   (This is the convention I have been using in my code for a while) 

Here is sketch of the two options:   [https://www.dropbox.com/s/iirsj9s3puwsfu5/sonar_orientation.png?dl=0](https://www.dropbox.com/s/iirsj9s3puwsfu5/sonar_orientation.png?dl=0)

I would love to hear everyone's thoughts!

**Comment by valschmidt** [comment]
Since this is fundamentally a push broom style sensor, I think "along track" and "across track" directions are unambiguous when speaking with respect to the sensor itself as we are, even for an upward looking, under ice, sonar. 
But I won't argue the point, and I like your definitions relative to the transmit array and receive array well enough. 

My preference to your suggestions is Proposal B (x-forward, y-stbd, z-down for a downward mounted system). This is in keeping with the POS/MV convention and that of Kongsberg. I think it also coincides with the SNAME convention for coordinate systems for modeling ships. 
[SNAME (1950). Nomenclature for Treating the Motion of a Submerged Body Through a Fluid. The Society of Naval Architects and Marine Engineers, Technical and Research Bulletin No. 1-5, April 1950, pp. 1-15.]

I will note, across the industry, the Caris convention is left handed, X to STBD, Y forward and Z down, the Hypack convention is right handed, or sometimes left-handed - it depends on the field. Some sonars vary still. It is a total shit-show that has caused no end of confusion for everyone. So if we can be clear, unambiguous, intuitive and in keeping with some stand convention - I'm all for it!

**Comment by lauralindzey** [comment]
Now that this conversation is starting, I'm realizing how wrong I was to lump all discussion of a single message into one issue -- these really should be separate issues, but I'm not sure how to fix it now.

**Regarding beam angles**: 
I think that it makes sense to use field names that *don't* map to the basic physics of the sensor, instead only referring to a coordinate system that has been defined. 

If we were considering this message in isolation, and expecting that it would only be used by a multibeam sonar, tx_angle and rx_angle would work. However, I imaging that the same driver may well want to publish a set of ranges (using SonarRanges.msg) and a full set of intensities (using SonarImage.msg). In that case, I think it would be confusing to have the field names differ between the two messages, and tx_angle and rx_angle don't map to the physics of an imaging sonar.

Similarly, I could imagine a narrow-aperture imaging sonar using this message to publish thresholded intensity data, in which case tx_array and rx_array is the wrong physical description of what's actually happening.

**Regarding coordinate frames:**

You're never going to get me to agree to support a left-handed coordinate system =) That way lies madness. More practically, we need to use one that's compatible with tf.

Overall in AUVs I usually see a forward/starboard/down system (or North/East/Down for globally referenced frames). So, I think the base_link frame in those sketches is wrong -- z should be down. This needs to be a top-level convention in the message design, so it might make sense to break that out into a separate issue.

For a sensor, I'm used to:
* The fan is in the x-y plane
* x is the direction in the center of the fan
* z is "down", which is a bit ambiguous. For forward-looking sonars, this is often obvious in the sensor

**Regarding message names**

The convention in sensor_msgs is to name the message after the type of data it contains, rather than making assumptions about exactly what sensor produced it. I don't think this is a binding convention.

**Comment by lauralindzey** [comment]
> Since this is fundamentally a push broom style sensor

In the bathymetric mapping context, yes ... but in the robotics context, not necessarily =) 

I worked on a robot where we mounted a multibeam with the fan pointed out the port side of the vehicle. The AUV then rolled to generate a 3D point cloud. 

I've also seen robots with a sonar mounted at the front of the vehicle on either a nodding or rotating platform, again to generate a 3D point cloud from a fundamentally 2D sensor.

The along/across track distinction would be confusing in either of these cases.

**Comment by CaptKrasno** [comment]
@valschmidt,   I am also a fan of proposal B.   

@valschmidt  and @lauralindzey:  I think I will make up a coordinate_conventions.md file and submit it to a pull request.   I want to define ground rules and conventions for all  acoustic sensors coordinate frames.    Keep an eye out for that, I am interest in your comments!

**Comment by lauralindzey** [comment]
@CaptKrasno -- thanks! That sounds like a great way to fork off at least that chunk from this sprawling discussion =)

**Comment by CaptKrasno** [comment]
> One other thing:
> 
> We are thinking to propose two message definitions for pointcloud2 messages for soundings from MBESs. One would be light-weight, and the second would include a 3x3 covariance for each sounding. The third would have a complete set of metadata (borrowing from SonarRanges) for troubleshooting. The repeated data structures would have the following fields (all float except `flag`). Your thoughts are welcome.
> 
> -Val
> 
> ```
>     # Msg 1
>     x
>     y
>     z
>     relative_intensity_dB
> 
>     # Msg 2         
>     x
>     y
>     z
>     relative_intensity_dB 
>     cov[[9]
>     
>     # Msg 3
>     x
>     y
>     z
>     cov[9]
>     relative_intensity_dB 
>     sound_speed
>     flag
>     elevation_angle
>     azimuth_angle
>     elevation_beamwidth
>     azimuth_beamwidth
>     two_way_travel_time
>     transmit_delay
> ```

Val I think this is a great idea!    I'm not sure where this belongs though.  It's kind of a half-processed data type since it needs to go through some projector.    Do we need an "acoustic_vis_msg" or something?    @valschmidt  @lauralindzey @bsb808   thoughts?

**Comment by lauralindzey** [comment]
@CaptKrasno @valschmidt -- Maybe create a separate Github Issue that lays out this proposal in more detail, with particular emphasis on the use cases? Then, when it's a bit better-defined, pull together a PR for discussion?

**Comment by CaptKrasno** [comment]
> @CaptKrasno @valschmidt -- Maybe create a separate Github Issue that lays out this proposal in more detail, with particular emphasis on the use cases? Then, when it's a bit better-defined, pull together a PR for discussion?

good Idea,  I will do this instead.

**Comment by CaptKrasno** [comment]
ok @lauralindzey @valschmidt ,   The proposal is up,   looking forward to your input.

**Comment by davecasa** [comment]
Is sonar _ranges_ the best term for this, considering that it's all time domain?

**Comment by lauralindzey** [comment]
@davecasa -- Can you clarify what you mean by "...considering that it's all time domain"?

In this case, "ranges" comes from the fact that this message definition is reporting a detected range to an obstacle for each beam, as opposed to other messages that report raw intensity data.

**Comment by lauralindzey** [comment]
Here's an attempt to summarize this sprawling (and excellent!) discussion, with suggestions for more atomic next steps.

1) Coordinate convention -- was previously forked to #8. For multibeams, that discussion seemed to converge on: Z centered in the fan, X is perpendicular to the fan pointed forward/up, and Y is defined to ensure a right-handed coordinate system.

2) Beam angle nomenclature -- was previously forked to #9, which converged to tx/rx for a multibeam. Next step is a PR to this repo changing it. I've added issue #15 to track that.

3) Renaming the message to reflect that it is very tightly coupled to a typical MBES system and actually reports TWTT. I agree, and forked to #16.

4) The intensity field name should include units to avoid avoid confusion. Seems like a good idea! -- forked to  #18

5) Potentially adding more fields -- forked to #19.

6) PR for @valschmidt's proposed pointcloud types? 

I'm not currently using a multibeam, so don't plan to address any of these changes myself. I think that fixes in the form of PRs would be welcome!

(Closing this issue since I think the discussion has stalled out, and that further discussions will be more targeted)
