### ISSUE TITLE
Proposed message ROS package layout.

### ISSUE THREAD

**Issue by bsb808** [apl-ocean-engineering/hydrographic_msgs#5]
Proposing for comment and organization of ROS packages for within the hydrographic_msgs repository.

To discuss or suggest, please work directly on google document: https://docs.google.com/document/d/1gVYhkOqTwjNw8gB8bMrVrKjwUnwLiVkIuDL-mddBv6w/edit?usp=sharing

**Comment by lauralindzey** [comment]
Based on comments on the linked google doc, I'd propose creating two packages for now:
* acoustic_msgs 
*  environmental_msgs
These are the categories that have concrete proposals for what messages should go in them. I also think that they're the highest-leverage messages to define, since they will enable sharing drivers and data. 

My only concern is whether the "environmental_msgs" name is specific enough -- do we want some clearer reference to being aquatic? oceanographic_msgs? uw_sensor_msgs?

**Comment by CaptKrasno** [comment]
I think environmental is fine.   Even the acoustic_msgs title could be applied outside oceanography.

**Comment by lauralindzey** [comment]
Given that there haven't been any new comments in months and we now have the acoustic_msgs and environmental_msgs subdirectories, I'm going to close this.

I think that the suggestions for vehicle_msgs and payload_msgs are good future steps, but sensors are the clear place to start, and should keep us busy for a while.
