### ISSUE TITLE
Git Workflow Guide

### ISSUE THREAD

**Issue by bsb808** [apl-ocean-engineering/hydrographic_msgs#7]
For community contributors, maintainers and developers, it would be nice to have shared expectations on the PR process.  

Here is what we use in the lab https://docs.google.com/document/d/1KnDST1Hvw4nklWUUCiBzbwm9qBcfnbpDuy15Sm3Xeik/edit?usp=sharing

If @lauralindzey and/or @CaptKrasno think it is worthwhile, I'll convert to md and submit as a PR.

**Comment by lauralindzey** [comment]
Sure, more detail about how we expect the PR process to go would probably be a good idea. The current description in the Contributors.md PR is a bit vague: "A PR will be merged when there is a critical mass of people supporting it.
When applicable, this includes commitments from owners of several repos using the affected message to update their code to match."

However, that document has a lot of details that assume you're going to be adding functionality to code, rather than changing interfaces, so it needs some editing first.

Maybe merge the existing (and imperfect) Contributors.md, and add a PR to the currently-skeletal section about the review process?

**Comment by lindzey** [comment]
Closing this issue -- a pared down version of that document is live at https://github.com/apl-ocean-engineering/hydrographic_msgs/blob/main/Contributing.md, and I think it's good enough for now.

**Comment by lauralindzey** [comment]
Closing this issue -- a pared down version of that document is live at https://github.com/apl-ocean-engineering/hydrographic_msgs/blob/main/Contributing.md, and I think it's good enough for now.
